### ISSUE TITLE
Could not find com.github.stellar:java-stellar-sdk:0.42.0.

### ISSUE THREAD

**Issue by rust-master** [stellar/kotlin-wallet-sdk#131]
I have added the org.stellar:wallet-sdk:1.5.0 in Kotlin project at gradle file that gives the below error

Error
```
Could not find com.github.stellar:java-stellar-sdk:0.42.0.
Required by:
    project :app > org.stellar:wallet-sdk:1.5.0
```

**Comment by Ifropc** [comment]
Make sure you have jitpack repo configured 
https://jitpack.io/#stellar/java-stellar-sdk
