### ISSUE TITLE
Why are functions marked suspend unnecessarily?

### ISSUE THREAD

**Issue by rahimklaber** [stellar/kotlin-wallet-sdk#90]
I was checking out the library and noticed that functions are marked suspend without needing to.

For example, [this function](https://github.com/stellar/kotlin-wallet-sdk/blob/7ef34b4c3d3cae84109c806bc92c9a9fb10cbf68/wallet-sdk/src/main/kotlin/org/stellar/walletsdk/extension/Server.kt#L34) is marked as suspend but does not actually use any suspend/coroutine functionality. In fact, the function seems to be doing a blocking IO operation, which should probably be wrapped in a `withContext(Dispatchers.IO)`.

**Comment by Ifropc** [comment]
Yes, it's a blocking IO operation. It's suspend so that external developer knows that it should be called from IO context. 
However, it is not mandatory, therefore we do not use any coroutine scope internally.
